blenv:
  version: '1'
environments:
  default:
    blender: /Applications/Blender.app/Contents/MacOS/Blender
    env_file: .env
    app_template: 'bl_music_player_app'
    addons:
      - music_player
project:
  addons:
    music_player:
      source: 'src/music_player'
  app_templates:
    bl_music_player_app:
      source: 'src/bl_music_player_app'
